services:
  app:
    image: jakac13/pritest:latest # uporabi build: . za zagon lokalnega Dockerfile
    container_name: pritest-container
    command: npm run nodemone
    ports:
      - 5000:3000
    volumes:
      - C:\Programiranje\Å ola\priTest:/usr/src/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: pritestDB
